### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by lqszsd** [startzm/captcha_cnn#3]
2022-01-13 11:21:55.444976: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-01-13 11:21:55.449508: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-01-13 11:21:57.719693: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-01-13 11:21:57.724222: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-13 11:21:57.729765: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 李棋GLKJ4845
2022-01-13 11:21:57.731740: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 李棋GLKJ4845
2022-01-13 11:21:57.733497: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
灏濊瘯鍔犺浇妯″瀷鏂囦欢..
鍔犺浇妯″瀷鎴愬姛
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
淇濆瓨妯″瀷鎴愬姛
<tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x000002ED973F7580>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 783, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2844, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\python_test\captcha_cnn\train_model.py", line 161, in <module>
    Train().train_model(config['max_epochs'])
  File "G:\python_test\captcha_cnn\train_model.py", line 73, in train_model
    self.valid_step(next(self.val_step))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 802, in __next__
    raise StopIteration
StopIteration

`import datetime
import json
import os

import tensorflow as tf
from tensorflow.keras import metrics
import numpy as np

from core.dataset import ImageDataSet
from core.model import CNN
from core.utils import CharAcc, ImgAcc

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Train:
    def __init__(self):
        # 初始化训练集、验证集
        self.train_set, self.valid_set = ImageDataSet().build()
        # 初始化模型
        self.model_save_dir = config['model_save_dir'] + '/model_weight'
        self.model = CNN(config['max_length'], len(config['char_set']))
        try:
            tf.print("尝试加载模型文件..")
            self.model.load_weights(self.model_save_dir)
            tf.print("加载模型成功")
        except:
            tf.print("未读取到模型文件..")
        # 初始化优化器
        self.optimizer = tf.keras.optimizers.Adam(lr=0.001)

        self.train_loss = metrics.Mean(name="train_loss")
        self.train_char_metric = CharAcc(name="train_char_accuracy")
        self.train_img_metric = ImgAcc(name="train_img_accuracy")

        self.valid_loss = metrics.Mean(name='valid_loss')
        self.valid_char_metric = CharAcc(name="valid_char_metric")
        self.valid_img_metric = ImgAcc(name="valid_img_metric")

        self.val_step = iter(self.valid_set)

        self.loss_list = [0]
        self.less_loss = 999
        self.wait = 0
        # 初始化tensorboard
        stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        self.summary_writer = tf.summary.create_file_writer(os.path.join("logs/"+stamp))

    def train_model(self, epoches):
        step = 0
        for epoch in range(1, epoches + 1):
            for x, y in self.train_set:
                with tf.GradientTape() as tape:
                    logits = self.model(x)
                    loss = tf.losses.categorical_crossentropy(y, logits)
                    loss = tf.reduce_mean(loss)
                # 每个step结束后原地更新梯度
                grads = tape.gradient(loss, self.model.trainable_variables)
                self.optimizer.apply_gradients(zip(grads, self.model.trainable_variables))

                if step % config["cycle_save"] == 0:
                    # 每训练达指定次数 自动保存模型
                    self.model.save_weights(self.model_save_dir)
                    tf.print("保存模型成功")
                    # 降低学习率
                    # self.optimizer.learning_rate = self.optimizer.learning_rate / 2

                if step % 10 == 0:
                    # 每训练10次 计算准确率并输入
                    self.train_char_metric.update_state(y, logits)
                    self.train_img_metric.update_state(y, logits)
                    print(self.val_step)
                    self.valid_step(next(self.val_step))

                    train_logs = '训练次数:{} \n训练集: Loss:{} 字符准确率: {}, 图片准确率: {}\n' \
                                 '验证集: Loss:{}, 字符准确率:{}, 图片准确率:{}\n'
                    tf.print("=========================================================")
                    tf.print(tf.strings.format(train_logs,
                                               (step, float(loss), self.train_char_metric.result(),
                                                self.train_img_metric.result(), self.valid_loss.result(),
                                                self.valid_char_metric.result(), self.valid_img_metric.result())))
                    self.write_summary(step, loss)

                    if float(self.train_char_metric.result()) >= float(config['acc_stop']):
                        tf.print("已经达到指定准确率，退出训练")
                        self.model.save_weights(self.model_save_dir)
                        tf.print("保存模型成功")
                        break
                    if self.early_stop(float(loss)):
                        tf.print("训练集loss已经不再提升，退出训练")
                        self.model.save_weights(self.model_save_dir)
                        tf.print("保存模型成功")
                        break

                    self.valid_loss.reset_states()
                    self.train_char_metric.reset_states()
                    self.valid_char_metric.reset_states()
                    self.train_img_metric.reset_states()
                    self.valid_img_metric.reset_states()

                step += 1
            else:
                continue
            break

    @tf.function
    def valid_step(self, data):
        features, labels = data
        predictions = self.model(features, training=False)
        loss = tf.reduce_mean(tf.losses.categorical_crossentropy(labels, predictions))

        self.valid_char_metric.update_state(labels, predictions)
        self.valid_img_metric.update_state(labels, predictions)
        self.valid_loss.update_state(loss)

    def early_stop(self, loss):
        # 提前停止训练
        if len(self.loss_list) > 10:
            self.loss_list[1:].append(loss - self.loss_list[-1])
        else:
            self.loss_list.append(loss - self.loss_list[-1])
        # 10轮以上loss更新均值低于loss_stop停止训练
        if abs(np.mean(self.loss_list)) < config['loss_stop']:
            return True
        # 10轮以上loss值不再降低则停止训练
        if self.less_loss != min(self.loss_list):
            # 临时保存最佳权重
            self.less_loss = loss
            self.best_weight = self.model.get_weights()
            self.wait = 0
        else:
            self.wait += 1
            if self.wait > 10:
                self.model.set_weights(self.best_weight)
                return True
        return False

    def write_summary(self, step, train_loss):
        # 写入tensorboard
        with self.summary_writer.as_default():
            tf.summary.scalar('train_loss', train_loss, step=step)
            tf.summary.scalar('train_char_accuracy', self.train_char_metric.result(), step=step)
            tf.summary.scalar('train_img_accuracy', self.train_img_metric.result(), step=step)

            tf.summary.scalar('valid_loss', self.valid_loss.result(), step=step)
            tf.summary.scalar('valid_char_accuracy', self.valid_char_metric.result(), step=step)
            tf.summary.scalar('valid_img_accuracy', self.valid_img_metric.result(), step=step)

if __name__ == '__main__':
    # 默认使用第0个GPU设备
    # physical_devices = tf.config.experimental.list_physical_devices('GPU')
    # assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
    # tf.config.experimental.set_memory_growth(physical_devices[0], True)

    # 加载配置文件
    with open("config.json", 'r') as f:
        config = json.load(f)

    # 训练
    Train().train_model(config['max_epochs'])

`

**Comment by startzm** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
